// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/boleto": {
            "post": {
                "description": "Retorna HTML ou PDF dependendo do parâmetro RetornarPDF",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/html",
                    "application/pdf"
                ],
                "tags": [
                    "boletos"
                ],
                "summary": "Gera um boleto bancário",
                "parameters": [
                    {
                        "description": "Dados do boleto",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BoletoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "PDF do boleto",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Erro de validação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/retorno/read": {
            "post": {
                "description": "Lê o conteúdo do arquivo de retorno bancário e extrai os boletos",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "retorno"
                ],
                "summary": "Processa arquivo de retorno",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Conteúdo do arquivo retorno (texto com múltiplas linhas)",
                        "name": "retorno",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.LinhaRetorno"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BoletoRequest": {
            "type": "object",
            "required": [
                "beneficiario_agencia",
                "beneficiario_cnpj_cpf",
                "beneficiario_conta",
                "beneficiario_nome",
                "codigo_banco",
                "convenio",
                "data_vencimento",
                "informacao_beneficiario",
                "nosso_numero",
                "numero_documento",
                "pagador_cpf",
                "pagador_nome",
                "parcela",
                "valor"
            ],
            "properties": {
                "beneficiario_agencia": {
                    "type": "string"
                },
                "beneficiario_cnpj_cpf": {
                    "type": "string",
                    "example": "12.345.678/0001-90"
                },
                "beneficiario_conta": {
                    "type": "string"
                },
                "beneficiario_endereco": {
                    "type": "string"
                },
                "beneficiario_nome": {
                    "type": "string",
                    "example": "Empresa Ltda"
                },
                "codigo_banco": {
                    "type": "string",
                    "example": "001-9"
                },
                "convenio": {
                    "type": "string",
                    "example": "12345"
                },
                "data_vencimento": {
                    "type": "string",
                    "example": "31/12/2025"
                },
                "identificador_pagador": {
                    "type": "integer"
                },
                "informacao_beneficiario": {
                    "type": "string",
                    "example": "Multa de 2% após vencimento"
                },
                "nosso_numero": {
                    "type": "string",
                    "example": "123456"
                },
                "numero_documento": {
                    "type": "string",
                    "example": "123456"
                },
                "pagador_cpf": {
                    "type": "string",
                    "example": "123.456.789-00"
                },
                "pagador_endereco": {
                    "type": "string"
                },
                "pagador_nome": {
                    "type": "string",
                    "example": "João da Silva"
                },
                "parcela": {
                    "type": "integer",
                    "example": 1
                },
                "retornar_pdf": {
                    "type": "boolean",
                    "example": true
                },
                "valor": {
                    "type": "string",
                    "example": "150,75"
                }
            }
        },
        "models.LinhaRetorno": {
            "type": "object",
            "properties": {
                "agencia_arrecadadora": {
                    "type": "string"
                },
                "codigo": {
                    "type": "string"
                },
                "codigo_barras": {
                    "type": "string"
                },
                "codigo_registro": {
                    "type": "string"
                },
                "data_credito": {
                    "type": "string"
                },
                "data_pagamento": {
                    "type": "string"
                },
                "forma_arrecadacao": {
                    "type": "string"
                },
                "forma_pagamento": {
                    "type": "string"
                },
                "identificacao": {
                    "type": "string"
                },
                "nsr": {
                    "type": "string"
                },
                "numero_autenticacao": {
                    "type": "string"
                },
                "parcela": {
                    "type": "integer"
                },
                "tarifa": {
                    "type": "number"
                },
                "valor_boleto": {
                    "type": "number"
                },
                "valor_pago": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Geração de Boletos",
	Description:      "API que recebe dados e gera um boleto em HTML.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
